### ISSUE TITLE
bug: bottom of interface cut off

### ISSUE THREAD

**Issue by cirrusflyer** [quickemu-project/quickgui#100]
See attached.   Can barely see bottom of interface.
![Screenshot from 2022-12-31 12-38-47](https://user-images.githubusercontent.com/33668552/210151595-dcd8db14-795d-4bf0-983d-2b40a39f24fb.png)

**Comment by glantucan** [comment]
The same happens to me. Also the window can't be resized. Is there any configuration file where this can be adjusted?

**Comment by Lazzu** [comment]
I have this issue as well, window can not be resized

**Comment by HunterShanks** [comment]
Has anyone found a fix for this yet? I'm experiencing the same issue.

**Comment by cirrusflyer** [comment]
Still broken for me.

**Comment by alexdelorenzo** [comment]
Encountering the same problem, not sure if it's a Flutter thing or not:
![Screenshot](https://user-images.githubusercontent.com/3579286/218354220-82626192-00fc-4724-b872-72bb9622d745.png)

Here's what I'm using it on:
```
KDE Plasma Version: 5.26.5
Qt Version: 5.15.
Graphics Platform: Wayland
````

**Comment by Codseus** [comment]
Same problem with zorin os 16.2 
![image](https://user-images.githubusercontent.com/27142266/220970606-ba9c8d7a-8c01-436a-b8aa-d63a4bd0bda3.png)

**Comment by arch-btw** [comment]
It's wayland related.

Try running this command:

>GDK_BACKEND=x11 quickgui

Or in KDE to set it permanently:

![image](https://user-images.githubusercontent.com/57669023/227629043-6ac6d271-ff38-4e0b-a1a4-a12e17cdd29a.png)

**Comment by HunterShanks** [comment]
> It's wayland related.
> 
> Try running this command:
> 
> > GDK_BACKEND=x11 quickgui
> 
> Or in KDE to set it permanently:
> 
> ![image](https://user-images.githubusercontent.com/57669023/227629043-6ac6d271-ff38-4e0b-a1a4-a12e17cdd29a.png)

I tried running the command and unfortunately it did not resolve the issue for me.

**Comment by dkburrows72** [comment]
Had this issue with Kubuntu / KDE Plasma 5.27. 3.  Changing the env variable did the trick for me.

**Comment by glantucan** [comment]
> It's wayland related.
> 
> Try running this command:
> 
> > GDK_BACKEND=x11 quickgui
> 
> Or in KDE to set it permanently:
> 
> ![image](https://user-images.githubusercontent.com/57669023/227629043-6ac6d271-ff38-4e0b-a1a4-a12e17cdd29a.png)

No, it's not, I'm afraid. I'm running over X11 and I have the same issue. I tried setting the environment variable, though,  but it does nothing for me.

**Comment by cirrusflyer** [comment]
Sure wish this could be fixed.

**Comment by cirrusflyer** [comment]
Please devs?  This is a big deal.

**Comment by DarkblooM-SR** [comment]
Same here on Pop!_OS 22.04 LTS (X11), can't resize or maximize the window for the life of me.

**Comment by delasalle-sio-paulin-i** [comment]
Same here on pop_os, it used to work properly before 
![Screenshot from 2023-11-02 18-24-43](https://github.com/quickemu-project/quickgui/assets/22473209/3babd3d2-3954-4b0a-b091-2fd4bc051486)

**Comment by 0Raik** [comment]
Manjaro Latest Gnome 46.1 Same as above. Gui not being Gui enough.

**Comment by flexiondotorg** [comment]
Tested on Ubuntu 22.04 and Ubuntu 24.04 with the Quickgui 1.2.9 release candidate and this issue is not presented. Fixed via https://github.com/quickemu-project/quickgui/commit/245c1f5251ce3e4ab24d2daecf3de645ec9f5a16

**Comment by certifiedfoolio** [comment]
Still having this, downloaded the rpm from the releases page...

**Comment by glantucan** [comment]
Quickgui 1.2.10. I'm still having this problem.
![image](https://github.com/user-attachments/assets/608b2994-8a06-407d-8c2f-227c9b199caa)
 Pop_os 22.04. Not using wayland
![image](https://github.com/user-attachments/assets/b09e36c6-7eb5-474b-bd26-c2ac06f1a6f2)
