### ISSUE TITLE
bug: some icons in the quickemu dark theme have incorrect contrast

### ISSUE THREAD

**Issue by flexiondotorg** [quickemu-project/quickgui#144]
The colours for the dark theme need some improvements, so the active and inactive state is clearly communicated.

**Comment by andypiper** [comment]
I just installed quickgui and went to enable dark mode (the correct mode), but found that the option is disabled. The reason was not completely clear until I found this issue and the associated commit. It may be better to remove the option rather than disabling it, to avoid similar confusion.

(the best approach would be to improve the colours or whatever else is required here; and then to follow the system light/dark preference).

**Comment by ivoheck** [comment]
I use QuickGUI regularly and was wondering why the dark mode switch wasn’t working. I saw this issue and would like to work on it. I'm new to open-source contributions—can I go ahead and fix this and open a PR? Let me know if there's anything specific I should keep in mind!

**Comment by boustanihani** [comment]
Same issue here, some icons are not visible at all. I'm using Gnome on Nix 24.11 (dark theme).

![Image](https://github.com/user-attachments/assets/38e59c12-19e4-43f0-95cf-cfb2e8a74285)

**Comment by boustanihani** [comment]
P.S. the dark theme in quickemu cannot be deactivated, the button simply doesn't move.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/quickemu-project/quickgui/pull/264

**Comment by boustanihani** [comment]
The dark theme in quickemu cannot be deactivated, the button simply doesn't move, this is still an issue.

I am using latest release: 1.2.10

<img width="692" height="580" alt="Image" src="https://github.com/user-attachments/assets/98a4e68c-dcef-4e9b-ac63-a29a2ca6ce9a" />

And this is my system:

<img width="1163" height="693" alt="Image" src="https://github.com/user-attachments/assets/a7ff510d-e9e3-4d05-8c30-44f00b58ca0b" />

**Comment by boustanihani** [comment]
> Same issue here, some icons are not visible at all. I'm using Gnome on Nix 24.11 (dark theme).
> 
> ![Image](https://github.com/user-attachments/assets/38e59c12-19e4-43f0-95cf-cfb2e8a74285)

And the issue with invisible icons persists..
