### ISSUE TITLE
Linux Mint 20.2 error GLibc 2.34

### ISSUE THREAD

**Issue by tudo75** [quickemu-project/quickgui#57]
Hi,
after the last update quickgui won't start on Linux Mint 20.2 due to the error 
<code>quickgui: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by quickgui)</code>

Mint latest glibc version is 2.31 (Mint is based on Ubuntu focal 20.04)
`ldd --version`
`ldd (Ubuntu GLIBC 2.31-0ubuntu9.2) 2.31`

**Comment by anyblabla** [comment]
Salvation. I came precisely to raise the problem, and I see that it has already been done! It's cool ;)

Error message: 
`quickgui: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.34' not found (required by quickgui)`

Linux Mint Uma 20.2 system, Ubuntu Focal 20.04.2 base.
`ldd --version`
`ldd (Ubuntu GLIBC 2.31-0ubuntu9.2) 2.31`

The two links which follow, it is to reward the work of the developer and all the people who maintain this beautiful project.
https://youtu.be/qeQ667zf74U
https://youtu.be/4klbTIIW5mg

**Comment by ymauray** [comment]
Oh merci !! Je vais immédiatement regarder cela avec intéret!

**Comment by ymauray** [comment]
And I will also have a look at that problem, of course :P

**Comment by ymauray** [comment]
Ok, I have confirmed the problem. I think I'll have to build on a focal VM for focal. Good thing that I know of a cool program to run VMs !! :P

**Comment by ymauray** [comment]
Alright, this has been fixed with release 1.2.1! Thanks for quickly reporting this problem! I hope this little downtime didn't impact you too much.

**Comment by anyblabla** [comment]
Many thanks for the very quick support !  Fortunately, you have THE ultimate virtualization software to quickly solve problems ;) It didn't impact me.  I could still present your project and its novelties, specifying that you are responsive ;) Good luck.

**Comment by tudo75** [comment]
Works now! Thanks for quick fix and for all your work

**Comment by gnuhead-chieb** [comment]
Still get this error

```
$ apt show quickgui
Package: quickgui
Version: 1.2.3-1~focal1.0
Priority: optional
Section: utils
Maintainer: Yannick Mauray <yannick.mauray@gmail.com>
Installed-Size: 24.7 MB
Depends: zenity
Download-Size: 7,216 kB
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/yannick-mauray/quickgui/ubuntu focal/main amd64 Packages
Description: A Flutter frontend for quickget

$ quickgui
quickgui: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by quickgui)

```
